/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XbalcAmbulanceLanding {
    }
    interface XbalcAmbulanceRekoEditor {
    }
    interface XbalcAmbulanceRekoList {
    }
}
declare global {
    interface HTMLXbalcAmbulanceLandingElement extends Components.XbalcAmbulanceLanding, HTMLStencilElement {
    }
    var HTMLXbalcAmbulanceLandingElement: {
        prototype: HTMLXbalcAmbulanceLandingElement;
        new (): HTMLXbalcAmbulanceLandingElement;
    };
    interface HTMLXbalcAmbulanceRekoEditorElement extends Components.XbalcAmbulanceRekoEditor, HTMLStencilElement {
    }
    var HTMLXbalcAmbulanceRekoEditorElement: {
        prototype: HTMLXbalcAmbulanceRekoEditorElement;
        new (): HTMLXbalcAmbulanceRekoEditorElement;
    };
    interface HTMLXbalcAmbulanceRekoListElement extends Components.XbalcAmbulanceRekoList, HTMLStencilElement {
    }
    var HTMLXbalcAmbulanceRekoListElement: {
        prototype: HTMLXbalcAmbulanceRekoListElement;
        new (): HTMLXbalcAmbulanceRekoListElement;
    };
    interface HTMLElementTagNameMap {
        "xbalc-ambulance-landing": HTMLXbalcAmbulanceLandingElement;
        "xbalc-ambulance-reko-editor": HTMLXbalcAmbulanceRekoEditorElement;
        "xbalc-ambulance-reko-list": HTMLXbalcAmbulanceRekoListElement;
    }
}
declare namespace LocalJSX {
    interface XbalcAmbulanceLanding {
    }
    interface XbalcAmbulanceRekoEditor {
    }
    interface XbalcAmbulanceRekoList {
    }
    interface IntrinsicElements {
        "xbalc-ambulance-landing": XbalcAmbulanceLanding;
        "xbalc-ambulance-reko-editor": XbalcAmbulanceRekoEditor;
        "xbalc-ambulance-reko-list": XbalcAmbulanceRekoList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "xbalc-ambulance-landing": LocalJSX.XbalcAmbulanceLanding & JSXBase.HTMLAttributes<HTMLXbalcAmbulanceLandingElement>;
            "xbalc-ambulance-reko-editor": LocalJSX.XbalcAmbulanceRekoEditor & JSXBase.HTMLAttributes<HTMLXbalcAmbulanceRekoEditorElement>;
            "xbalc-ambulance-reko-list": LocalJSX.XbalcAmbulanceRekoList & JSXBase.HTMLAttributes<HTMLXbalcAmbulanceRekoListElement>;
        }
    }
}
